--- #deleting the file
- name: to delete the dir
  hosts: all
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: creating a directory
      file:
        path: /home/ansible/myfolder
        state: absent

