--- # my handler playbook season
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: installing hhtpd package into hosts
      action: yum name=httpd state=present
      notify: start httpd service

  handlers:
    - name: start httpd service
      action: service name=httpd state=started
