--- # my onemore conditional playbook
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: installing httpd in redhat
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == 'RedHat'
   
    - name: service httpd start
      service:
        name: httpd
        state: started
      when: ansible_os_family == 'RedHat'

    - name: installing apache2 in 
      apt:
        name: apache2
        state: present
      when: ansible_os_family == 'Debian'

    - name: service apache2 start
      service:
        name: apache2
        state: started
      when: ansible_os_family == 'Debian'


    - name: copy index.html to host
      copy:
        src: /home/ansible/index.html
        dest: /var/www/html
        owner: sunny




