--- #for creating task
- hosts: all
  user: ansible
  become: yes
  connection: ssh


  tasks: 
    - name: installing httpd software in webservers
      action: yum name=http state=installed
      ignore_errors: yes

